import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "Sate Soto Madura Mas Niram, Melania",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <header>
          <div className="border-b flex justify-center p-4">
            <h1 className="text-xl font-bold md:text-2xl">
              Sate Soto Madura Mas Niram, Melania
            </h1>
          </div>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
